const itemsData = [
  {
    idName: "Spinery Kolekcja 3D Multikolor 10'",
    imgSource: "",
    dataOwncode: "",
    dataCode: "",
    dataName: "",
    dataItemsize: "",
    dataItemcolor: "",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 3D Multikolor 10'",
    imgSource: "./mini_spinners/Mini D6010 Motyl 3D.png",
    dataOwncode: "3100",
    dataCode: "D6010",
    dataName: "Motyl 3D",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 3D Multikolor 10'",
    imgSource: "./mini_spinners/Mini D6025 Ważka w trzcinie 3D.png",
    dataOwncode: "3101",
    dataCode: "D6025",
    dataName: "Ważki-trzciny 3D",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 3D Multikolor 10'",
    imgSource: "./mini_spinners/Mini D6031 Wróżki 3D.png",
    dataOwncode: "3102",
    dataCode: "D6031",
    dataName: "Wróżki 3D",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 3D Multikolor 10'",
    imgSource: "./mini_spinners/Mini D6135 Koliber 3D.jpg",
    dataOwncode: "3103",
    dataCode: "D6135",
    dataName: "Koliber 3D",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 3D Multikolor 10'",
    imgSource: "./mini_spinners/Mini ED092 Wróżki 3D.jpg",
    dataOwncode: "3104",
    dataCode: "ED092",
    dataName: "Wróżki 3D",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 3D Multikolor 10'",
    imgSource: "./mini_spinners/Mini ED079 Ptaszek 3D.jpg",
    dataOwncode: "3105",
    dataCode: "ED079",
    dataName: "Ptaszek 3D",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 3D Multikolor 10'",
    imgSource: "./mini_spinners/Mini ED077 Motyl 3D.jpg",
    dataOwncode: "3106",
    dataCode: "ED077",
    dataName: "Motyl 3D",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },

  {
    idName: "Spinery Kolekcja 3D Multikolor 10'",
    imgSource: "./mini_spinners/Mini ED078 Ważka 3D.jpg",
    dataOwncode: "3107",
    dataCode: "ED078",
    dataName: "Ważka 3D",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 3D Multikolor 10'",
    imgSource: "./mini_spinners/Mini D6145 Sun Ray 3D.png",
    dataOwncode: "3108",
    dataCode: "D6145",
    dataName: "Sun Ray 3D",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 3D Multikolor 10'",
    imgSource: "./mini_spinners/Mini D6125 Ważka 3D.jpg",
    dataOwncode: "3109",
    dataCode: "D6125",
    dataName: "Ważka 3D",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 3D Multikolor 10'",
    imgSource: "./mini_spinners/Mini D6110 Motyl multi.jpg",
    dataOwncode: "3110",
    dataCode: "D6110",
    dataName: "Motyl 3D",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },

  {
    idName: "Spinery Kolekcja GB Multikolor 12'",
    imgSource: "",
    dataOwncode: "",
    dataCode: "",
    dataName: "",
    dataItemsize: "",
    dataItemcolor: "",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja GB Multikolor 12'",
    imgSource: "./mini_spinners/Mini D1525 Kwiat GB.jpg",
    dataOwncode: "3151",
    dataCode: "D1525",
    dataName: "Kwiat GB",
    dataItemsize: "12",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja GB Multikolor 12'",
    imgSource: "./mini_spinners/Mini D1538 TeardropGB.JPG",
    dataOwncode: "3154",
    dataCode: "D1538",
    dataName: "Teardrop GB",
    dataItemsize: "12",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja GB Multikolor 12'",
    imgSource: "./mini_spinners/Mini D7538 Teardrop.jpg",
    dataOwncode: "3158",
    dataCode: "D7538",
    dataName: "Teardrop GB",
    dataItemsize: "12",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },

  {
    idName: "Spinery Kolekcja GB Multikolor 10'",
    imgSource: "",
    dataOwncode: "",
    dataCode: "",
    dataName: "",
    dataItemsize: "",
    dataItemcolor: "",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja GB Multikolor 10'",
    imgSource: "./mini_spinners/Mini D1515 Motyl.jpg",
    dataOwncode: "3150",
    dataCode: "D1515",
    dataName: "Motyl GB",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja GB Multikolor 10'",
    imgSource: "./mini_spinners/Mini D1532 Splash.jpg",
    dataOwncode: "3152",
    dataCode: "D1532",
    dataName: "Splash GB",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja GB Multikolor 10'",
    imgSource: "./mini_spinners/Mini D1535 Słońce GB.jpg",
    dataOwncode: "3153",
    dataCode: "D1535",
    dataName: "Słońce GB",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja GB Multikolor 10'",
    imgSource: "./mini_spinners/Mini D7515 Motyl.jpg",
    dataOwncode: "3155",
    dataCode: "D7515",
    dataName: "Motyl GB",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja GB Multikolor 10'",
    imgSource: "./mini_spinners/Mini D7525 Kwiat GB.jpg",
    dataOwncode: "3156",
    dataCode: "D7525",
    dataName: "Kwiat GB",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja GB Multikolor 10'",
    imgSource: "./mini_spinners/Mini D7532 Splash GB.jpg",
    dataOwncode: "3157",
    dataCode: "D7532",
    dataName: "Splash GB",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja GB Multikolor 10'",
    imgSource: "./mini_spinners/Mini ED016 Słonce.jpg",
    dataOwncode: "3159",
    dataCode: "ED016",
    dataName: "Słońce GB",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja GB Multikolor 10'",
    imgSource: "./mini_spinners/Mini ED018 teardrop GB multikolor.jpg",
    dataOwncode: "3160",
    dataCode: "ED018",
    dataName: "Teardrop GB",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja GB Multikolor 10'",
    imgSource: "./mini_spinners/Mini ED056 Romb GB.jpg",
    dataOwncode: "3161",
    dataCode: "ED056",
    dataName: "Romb GB",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja GB Multikolor 10'",
    imgSource: "./mini_spinners/Mini ED040 Square.jpg",
    dataOwncode: "3162",
    dataCode: "ED040",
    dataName: "Square GB",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja GB Multikolor 10'",
    imgSource: "./mini_spinners/Mini ED070 Kwiat GB.jpg",
    dataOwncode: "3163",
    dataCode: "ED070",
    dataName: "Kwiat GB",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja GB Multikolor 10'",
    imgSource: "./mini_spinners/Mini ED017 splash GB multikolor.jpg",
    dataOwncode: "3164",
    dataCode: "ED017",
    dataName: "Kwiat GB",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja GB Multikolor 10'",
    imgSource: "./mini_spinners/Mini ED095 Flat.jpg",
    dataOwncode: "3165",
    dataCode: "ED095",
    dataName: "Flat GB",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja GB Multikolor 10'",
    imgSource: "./mini_spinners/Mini ED115 Leaf.jpg",
    dataOwncode: "3166",
    dataCode: "ED115",
    dataName: "Leaf GB",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja GB Multikolor 10'",
    imgSource: "./mini_spinners/Mini ED121 Quatro GB.jpg",
    dataOwncode: "3167",
    dataCode: "ED121",
    dataName: "Quatro GB",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja GB Multikolor 10'",
    imgSource: "./mini_spinners/Mini ED124 Kwiat GB.jpg",
    dataOwncode: "3168",
    dataCode: "ED124",
    dataName: "Kwiat GB",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "",
    dataOwncode: "",
    dataCode: "",
    dataName: "",
    dataItemsize: "",
    dataItemcolor: "",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "./mini_spinners/Mini D020 Anioł.png",
    dataOwncode: "3000",
    dataCode: "D020",
    dataName: "Anioł",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "./mini_spinners/Mini D283 Cosmicksplash.jpg",
    dataOwncode: "3001",
    dataCode: "D283",
    dataName: "CosmicSplash",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },

  {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "./mini_spinners/Mini D331 Galacticsplash.jpg",
    dataOwncode: "3003",
    dataCode: "D331",
    dataName: "GalacticSplash",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "./mini_spinners/Mini D220 Serce.png",
    dataOwncode: "3004",
    dataCode: "D220",
    dataName: "Serce",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "./mini_spinners/Mini D120 Motyl.png",
    dataOwncode: "3005",
    dataCode: "D120",
    dataName: "Motyl",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "./mini_spinners/Mini D250 Koliber.jpg",
    dataOwncode: "3006",
    dataCode: "D250",
    dataName: "Koliber",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "./mini_spinners/Mini D258 Hypersplash.jpg",
    dataOwncode: "3007",
    dataCode: "D258",
    dataName: "HyperSplash",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "./mini_spinners/Mini D315 Słońce.png",
    dataOwncode: "3008",
    dataCode: "D315",
    dataName: "Słońce",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "./mini_spinners/Mini D351 Teardrop.jpg",
    dataOwncode: "3009",
    dataCode: "D351",
    dataName: "Teardrop",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "./mini_spinners/Mini D282 Lunarsplash.png",
    dataOwncode: "3010",
    dataCode: "D282",
    dataName: "LunarSplash",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "./mini_spinners/Mini ED012 Sunsplash.jpg",
    dataOwncode: "3011",
    dataCode: "ED012",
    dataName: "SunSplash",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "./mini_spinners/Mini ED013 splash multikolor.jpg",
    dataOwncode: "3012",
    dataCode: "ED013",
    dataName: "Splash",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "./mini_spinners/Mini ED131 Konie multi.jpg",
    dataOwncode: "3013",
    dataCode: "ED131",
    dataName: "Konie",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "./mini_spinners/Mini D260 Lotus.png",
    dataOwncode: "3014",
    dataCode: "D260",
    dataName: "Lotus",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "./mini_spinners/Mini ED108 David.jpg",
    dataOwncode: "3015",
    dataCode: "ED108",
    dataName: "David",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "./mini_spinners/Mini ED103 Kula MK.jpg",
    dataOwncode: "3016",
    dataCode: "ED103",
    dataName: "Kula",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "./mini_spinners/Mini ED055 Romb.jpg",
    dataOwncode: "3017",
    dataCode: "ED055",
    dataName: "Romb",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "./mini_spinners/Mini ED117 rombo multikolor.jpg",
    dataOwncode: "3018",
    dataCode: "ED117",
    dataName: "Rombo",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "./mini_spinners/Mini D280 Księżyc.png",
    dataOwncode: "3019",
    dataCode: "D280",
    dataName: "Księżyc",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "./mini_spinners/Mini ED089 Słońce.jpg",
    dataOwncode: "3020",
    dataCode: "ED089",
    dataName: "Słońce",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "",
    dataOwncode: "3021",
    dataCode: "ED500",
    dataName: "Sowa",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "./mini_spinners/Mini ED200 Traktor.jpg",
    dataOwncode: "3041",
    dataCode: "ED200",
    dataName: "Traktor",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  }, {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "./mini_spinners/Mini ED201 Żaglówka.jpg",
    dataOwncode: "3042",
    dataCode: "ED201",
    dataName: "Żaglówka",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "./mini_spinners/Mini ED202 Latarnia 2.jpg",
    dataOwncode: "3043",
    dataCode: "ED202",
    dataName: "Latarnia",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "./mini_spinners/Mini ED203 Jeleń.jpg",
    dataOwncode: "3044",
    dataCode: "ED203",
    dataName: "Jeleń",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "./mini_spinners/Mini ED204_10 MixSplash.jpg",
    dataOwncode: "3045",
    dataCode: "ED204",
    dataName: "MixSplash",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "./mini_spinners/Mini ED205 Ptaszek.jpg",
    dataOwncode: "3047",
    dataCode: "ED205",
    dataName: "Ptaszek",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "./mini_spinners/Mini ED206 Super Sun.jpg",
    dataOwncode: "3046",
    dataCode: "ED206",
    dataName: "SuperSun",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  // {
  //   idName: "Spinery Kolekcja 2D Multikolor 10'",
  //   imgSource: "",
  //   dataOwncode: "",
  //   dataCode: "",
  //   dataName: "",
  //   dataItemsize: "",
  //   dataItemcolor: "",
  //   dataQuantity: "",
  //   dataRemarks: "",
  // },
  {
    idName: "Spinery Kolekcja 2D Multikolor 6'",
    imgSource: "",
    dataOwncode: "",
    dataCode: "",
    dataName: "",
    dataItemsize: "",
    dataItemcolor: "",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 6'",
    imgSource: "./mini_spinners/Mini D020 Anioł.png",
    dataOwncode: "3000",
    dataCode: "D020",
    dataName: "Anioł",
    dataItemsize: "6",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 6'",
    imgSource: "./mini_spinners/Mini D283 Cosmicksplash.jpg",
    dataOwncode: "3001",
    dataCode: "D283",
    dataName: "CosmicSplash",
    dataItemsize: "6",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 6'",
    imgSource: "./mini_spinners/Mini D157 Zaba.jpg",
    dataOwncode: "3002",
    dataCode: "D157",
    dataName: "Żaba",
    dataItemsize: "6",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 10'",
    imgSource: "./mini_spinners/Mini D331 Galacticsplash.jpg",
    dataOwncode: "3003",
    dataCode: "D331",
    dataName: "GalacticSplash",
    dataItemsize: "10",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 6'",
    imgSource: "./mini_spinners/Mini D220 Serce.png",
    dataOwncode: "3004",
    dataCode: "D220",
    dataName: "Serce",
    dataItemsize: "6",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 6'",
    imgSource: "./mini_spinners/Mini D120 Motyl.png",
    dataOwncode: "3005",
    dataCode: "D120",
    dataName: "Motyl",
    dataItemsize: "6",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 6'",
    imgSource: "./mini_spinners/Mini D250 Koliber.jpg",
    dataOwncode: "3006",
    dataCode: "D250",
    dataName: "Koliber",
    dataItemsize: "6",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 6'",
    imgSource: "./mini_spinners/Mini D258 Hypersplash.jpg",
    dataOwncode: "3007",
    dataCode: "D258",
    dataName: "HyperSplash",
    dataItemsize: "6",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 6'",
    imgSource: "./mini_spinners/Mini D315 Słońce.png",
    dataOwncode: "3008",
    dataCode: "D315",
    dataName: "Słońce",
    dataItemsize: "6",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 6'",
    imgSource: "./mini_spinners/Mini D351 Teardrop.jpg",
    dataOwncode: "3009",
    dataCode: "D351",
    dataName: "Teardrop",
    dataItemsize: "6",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 6'",
    imgSource: "./mini_spinners/Mini D282 Lunarsplash.png",
    dataOwncode: "3010",
    dataCode: "D282",
    dataName: "LunarSplash",
    dataItemsize: "6",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 6'",
    imgSource: "./mini_spinners/Mini ED012 Sunsplash.jpg",
    dataOwncode: "3011",
    dataCode: "ED012",
    dataName: "SunSplash",
    dataItemsize: "6",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 6'",
    imgSource: "./mini_spinners/Mini ED013 splash multikolor.jpg",
    dataOwncode: "3012",
    dataCode: "ED013",
    dataName: "Splash",
    dataItemsize: "6",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 6'",
    imgSource: "./mini_spinners/Mini ED131 Konie multi.jpg",
    dataOwncode: "3013",
    dataCode: "ED131",
    dataName: "Konie",
    dataItemsize: "6",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },

  {
    idName: "Spinery Kolekcja 2D Multikolor 6'",
    imgSource: "./mini_spinners/Mini ED108 David.jpg",
    dataOwncode: "3015",
    dataCode: "ED108",
    dataName: "David",
    dataItemsize: "6",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 6'",
    imgSource: "./mini_spinners/Mini ED103 Kula MK.jpg",
    dataOwncode: "3016",
    dataCode: "ED103",
    dataName: "Kula",
    dataItemsize: "6",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 6'",
    imgSource: "./mini_spinners/Mini ED055 Romb.jpg",
    dataOwncode: "3017",
    dataCode: "ED055",
    dataName: "Romb",
    dataItemsize: "6",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 6'",
    imgSource: "./mini_spinners/Mini ED117 rombo multikolor.jpg",
    dataOwncode: "3018",
    dataCode: "ED117",
    dataName: "Rombo",
    dataItemsize: "6",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Kolekcja 2D Multikolor 6'",
    imgSource: "./mini_spinners/Mini D280 Księżyc.png",
    dataOwncode: "3019",
    dataCode: "D280",
    dataName: "Księżyc",
    dataItemsize: "6",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },

  {
    idName: "Spinery Multikolor 6'",
    imgSource: "./mini_spinners/Mini ED200 Traktor.jpg",
    dataOwncode: "3041",
    dataCode: "ED200",
    dataName: "Traktor",
    dataItemsize: "6",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  }, {
    idName: "Spinery Multikolor 6'",
    imgSource: "./mini_spinners/Mini ED201 Żaglówka.jpg",
    dataOwncode: "3042",
    dataCode: "ED201",
    dataName: "Żaglówka",
    dataItemsize: "6",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Multikolor 6'",
    imgSource: "./mini_spinners/Mini ED202 Latarnia 2.jpg",
    dataOwncode: "3043",
    dataCode: "ED202",
    dataName: "Latarnia",
    dataItemsize: "6",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Multikolor 6'",
    imgSource: "./mini_spinners/Mini ED203 Jeleń.jpg",
    dataOwncode: "3044",
    dataCode: "ED203",
    dataName: "Jeleń",
    dataItemsize: "6",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Multikolor 6'",
    imgSource: "./mini_spinners/Mini ED204_10 MixSplash.jpg",
    dataOwncode: "3045",
    dataCode: "ED204",
    dataName: "MixSplash",
    dataItemsize: "6",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Multikolor 6'",
    imgSource: "./mini_spinners/Mini ED205 Ptaszek.jpg",
    dataOwncode: "3047",
    dataCode: "ED205",
    dataName: "Ptaszek",
    dataItemsize: "6",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
  {
    idName: "Spinery Multikolor 6'",
    imgSource: "./mini_spinners/Mini ED206 Super Sun.jpg",
    dataOwncode: "3046",
    dataCode: "ED206",
    dataName: "SuperSun",
    dataItemsize: "6",
    dataItemcolor: "Multikolor",
    dataQuantity: "",
    dataRemarks: "",
  },
];

export default itemsData;